//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EODbModel", "StarterCompetitionAss", "Starter", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EventOrganizer.Starter), "StarterCompetition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EventOrganizer.StarterCompetition), true)]
[assembly: EdmRelationshipAttribute("EODbModel", "CompetitionStarterCompetition", "Competition", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EventOrganizer.Competition), "StarterCompetition", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EventOrganizer.StarterCompetition), true)]

#endregion

namespace EventOrganizer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EODbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EODbEntities object using the connection string found in the 'EODbEntities' section of the application configuration file.
        /// </summary>
        public EODbEntities() : base("name=EODbEntities", "EODbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EODbEntities object.
        /// </summary>
        public EODbEntities(string connectionString) : base(connectionString, "EODbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EODbEntities object.
        /// </summary>
        public EODbEntities(EntityConnection connection) : base(connection, "EODbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Competition> Competition
        {
            get
            {
                if ((_Competition == null))
                {
                    _Competition = base.CreateObjectSet<Competition>("Competition");
                }
                return _Competition;
            }
        }
        private ObjectSet<Competition> _Competition;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Starter> Starter
        {
            get
            {
                if ((_Starter == null))
                {
                    _Starter = base.CreateObjectSet<Starter>("Starter");
                }
                return _Starter;
            }
        }
        private ObjectSet<Starter> _Starter;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StarterCompetition> StarterCompetition
        {
            get
            {
                if ((_StarterCompetition == null))
                {
                    _StarterCompetition = base.CreateObjectSet<StarterCompetition>("StarterCompetition");
                }
                return _StarterCompetition;
            }
        }
        private ObjectSet<StarterCompetition> _StarterCompetition;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Competition EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompetition(Competition competition)
        {
            base.AddObject("Competition", competition);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Starter EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStarter(Starter starter)
        {
            base.AddObject("Starter", starter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StarterCompetition EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStarterCompetition(StarterCompetition starterCompetition)
        {
            base.AddObject("StarterCompetition", starterCompetition);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EODbModel", Name="Competition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Competition : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Competition object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="caption">Initial value of the Caption property.</param>
        public static Competition CreateCompetition(global::System.Int64 id, global::System.String caption)
        {
            Competition competition = new Competition();
            competition.Id = id;
            competition.Caption = caption;
            return competition;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Caption
        {
            get
            {
                return _Caption;
            }
            set
            {
                OnCaptionChanging(value);
                ReportPropertyChanging("Caption");
                _Caption = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Caption");
                OnCaptionChanged();
            }
        }
        private global::System.String _Caption;
        partial void OnCaptionChanging(global::System.String value);
        partial void OnCaptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EODbModel", "CompetitionStarterCompetition", "StarterCompetition")]
        public EntityCollection<StarterCompetition> StarterCompetition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StarterCompetition>("EODbModel.CompetitionStarterCompetition", "StarterCompetition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StarterCompetition>("EODbModel.CompetitionStarterCompetition", "StarterCompetition", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EODbModel", Name="Starter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Starter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Starter object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static Starter CreateStarter(global::System.Int64 id, global::System.String firstName, global::System.String lastName)
        {
            Starter starter = new Starter();
            starter.Id = id;
            starter.FirstName = firstName;
            starter.LastName = lastName;
            return starter;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthdate
        {
            get
            {
                return _Birthdate;
            }
            set
            {
                OnBirthdateChanging(value);
                ReportPropertyChanging("Birthdate");
                _Birthdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthdate");
                OnBirthdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthdate;
        partial void OnBirthdateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Club
        {
            get
            {
                return _Club;
            }
            set
            {
                OnClubChanging(value);
                ReportPropertyChanging("Club");
                _Club = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Club");
                OnClubChanged();
            }
        }
        private global::System.String _Club;
        partial void OnClubChanging(global::System.String value);
        partial void OnClubChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pony
        {
            get
            {
                return _Pony;
            }
            set
            {
                OnPonyChanging(value);
                ReportPropertyChanging("Pony");
                _Pony = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pony");
                OnPonyChanged();
            }
        }
        private global::System.String _Pony;
        partial void OnPonyChanging(global::System.String value);
        partial void OnPonyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EODbModel", "StarterCompetitionAss", "StarterCompetition")]
        public EntityCollection<StarterCompetition> StarterCompetition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StarterCompetition>("EODbModel.StarterCompetitionAss", "StarterCompetition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StarterCompetition>("EODbModel.StarterCompetitionAss", "StarterCompetition", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EODbModel", Name="StarterCompetition")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StarterCompetition : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StarterCompetition object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="starterId">Initial value of the StarterId property.</param>
        /// <param name="competitionId">Initial value of the CompetitionId property.</param>
        public static StarterCompetition CreateStarterCompetition(global::System.Int64 id, global::System.Int64 starterId, global::System.Int64 competitionId)
        {
            StarterCompetition starterCompetition = new StarterCompetition();
            starterCompetition.Id = id;
            starterCompetition.StarterId = starterId;
            starterCompetition.CompetitionId = competitionId;
            return starterCompetition;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 StarterId
        {
            get
            {
                return _StarterId;
            }
            set
            {
                OnStarterIdChanging(value);
                ReportPropertyChanging("StarterId");
                _StarterId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StarterId");
                OnStarterIdChanged();
            }
        }
        private global::System.Int64 _StarterId;
        partial void OnStarterIdChanging(global::System.Int64 value);
        partial void OnStarterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CompetitionId
        {
            get
            {
                return _CompetitionId;
            }
            set
            {
                OnCompetitionIdChanging(value);
                ReportPropertyChanging("CompetitionId");
                _CompetitionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompetitionId");
                OnCompetitionIdChanged();
            }
        }
        private global::System.Int64 _CompetitionId;
        partial void OnCompetitionIdChanging(global::System.Int64 value);
        partial void OnCompetitionIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EODbModel", "StarterCompetitionAss", "Starter")]
        public Starter Starter
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Starter>("EODbModel.StarterCompetitionAss", "Starter").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Starter>("EODbModel.StarterCompetitionAss", "Starter").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Starter> StarterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Starter>("EODbModel.StarterCompetitionAss", "Starter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Starter>("EODbModel.StarterCompetitionAss", "Starter", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EODbModel", "CompetitionStarterCompetition", "Competition")]
        public Competition Competition
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competition>("EODbModel.CompetitionStarterCompetition", "Competition").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competition>("EODbModel.CompetitionStarterCompetition", "Competition").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Competition> CompetitionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Competition>("EODbModel.CompetitionStarterCompetition", "Competition");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Competition>("EODbModel.CompetitionStarterCompetition", "Competition", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
